version: '3.8'

services:
  message-db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mdb
      POSTGRES_USER: mdb
      POSTGRES_PASSWORD: mdb
    volumes:
      - message-db-data:/var/lib/postgresql/data:cached
      - ./init-message-db.sh:/docker-entrypoint-initdb.d/init-message-db.sh

volumes:
  message-db-data:
